### ISSUE TITLE
Updates to handle user/group/extras changes in `crane`

### ISSUE THREAD

**Issue by djzager** [konveyor/gitops-primer#173]
When https://github.com/konveyor/crane/pull/68 updates `crane` to mimic `kubectl` in it's handling of context, namespace, kubeconfig, and user impersonation capabilities. It does so be leveraging completely the `genericclioptions.ConfigFlags` this means that:

* `as-user` -> `as`
* `as-group` stays the same
* `as-extras` stays the same

**Comment by djzager** [comment]
cc @shawn-hurley 

I want to add more detail but figured making sure it exists (before I forget entirely) was better than nothing :sunglasses:

**Comment by djzager** [comment]
Looking around the source. This change become essential for https://github.com/konveyor/gitops-primer/blob/210dd792a04e8ef4468b5590acdee77bff15fdd1/export/committer.sh#L75 as soon as crane is updated here https://github.com/konveyor/gitops-primer/blob/210dd792a04e8ef4468b5590acdee77bff15fdd1/export/Dockerfile#L4

**Comment by cooktheryan** [comment]
@djzager fixed in main now. Closing
